# Generated by Django 5.1.4 on 2024-12-24 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('application', models.CharField(max_length=100)),
                ('cpu', models.CharField(max_length=50)),
                ('storage', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=100)),
                ('installed_packages', models.TextField()),
                ('date_put_in_service', models.DateField()),
                ('date_to_retire', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
